apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090