apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: udacity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090