# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  install-dependencies:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: setup env
          command: |
            make setup
      - run:
          name: install dependencies
          command: |
            make install
      - save_cache:
          paths:
            - ./udacity
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  lint-code:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./udacity
      - run:
          name: run lint
          command: |
            make lint

workflows:
  default:
    jobs:
      # - node-exporter
      - install-dependencies
      - lint-code:
          requires: [install-dependencies]
