# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  install-dependencies:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: setup env
          command: |
            make setup
      - run:
          name: install dependencies
          command: |
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  lint-code:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  build-image:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run: docker build -t udacity-capstone:$CIRCLE_BRANCH .

      - run: docker push udacity-capstone:$CIRCLE_BRANCH

workflows:
  default:
    jobs:
      # - node-exporter
      - install-dependencies
      - lint-code:
          requires: [install-dependencies]
      - build-image:
          requires: [lint-code]
